// Code generated by monitor-code-gen. DO NOT EDIT.

package mongodb

import (
	"github.com/signalfx/golib/v3/datapoint"
	"github.com/signalfx/signalfx-agent/pkg/monitors"
)

const monitorType = "telegraf/mongodb"

var groupSet = map[string]bool{}

const (
	mongodbCommands             = "mongodb.commands"
	mongodbConnectionsAvailable = "mongodb.connections_available"
	mongodbConnectionsCurrent   = "mongodb.connections_current"
	mongodbMemberStatus         = "mongodb.member_status"
	mongodbReplLag              = "mongodb.repl_lag"
	mongodbReplState            = "mongodb.repl_state"
)

var metricSet = map[string]monitors.MetricInfo{
	mongodbCommands:             {Type: datapoint.Gauge},
	mongodbConnectionsAvailable: {Type: datapoint.Gauge},
	mongodbConnectionsCurrent:   {Type: datapoint.Gauge},
	mongodbMemberStatus:         {Type: datapoint.Gauge},
	mongodbReplLag:              {Type: datapoint.Gauge},
	mongodbReplState:            {Type: datapoint.Gauge},
}

var defaultMetrics = map[string]bool{
	mongodbCommands:             true,
	mongodbConnectionsAvailable: true,
	mongodbConnectionsCurrent:   true,
	mongodbMemberStatus:         true,
	mongodbReplLag:              true,
	mongodbReplState:            true,
}

var groupMetricsMap = map[string][]string{}

var monitorMetadata = monitors.Metadata{
	MonitorType:     "telegraf/mongodb",
	DefaultMetrics:  defaultMetrics,
	Metrics:         metricSet,
	SendUnknown:     false,
	Groups:          groupSet,
	GroupMetricsMap: groupMetricsMap,
	SendAll:         false,
}
